version: '3.9'

services:
  postgres-docker:
    image: postgres:15.8
    container_name: bd-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=medapi
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  flyway:
    image: flyway/flyway:9.6
    container_name: flyway
    depends_on:
      - postgres-docker
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres-docker:5432/medapi
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: root
      FLYWAY_SCHEMAS: public
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - app-network
    command: -baselineOnMigrate=true migrate

  redis:
    image: redis:7.2.2
    container_name: redis-server
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge